export { Table } from "./table"
export { Th } from "./table"
export { Td } from "./table"
export { Tbody } from "./table"
export { Thead } from "./table"
export { DeleteBtn } from "./buttons"
export { EditBtn } from "./buttons"